apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../
namePrefix: prod-
helmCharts:
  - name: sample-chart
    releaseName: my-app
    valuesFile: values.yaml
namespace: prod-namespace
labels:
  - includeSelectors: true
    pairs:
      env: production
