resources:
  - ../../base
images:
  - name: nginx:stable-alpine3.23-perl
    newName: backend-prod
    newTag: v1.0.0
replicas:
  - name: myapp
    count: 10
configMapGenerator:
  - name: app-config
    files:
      - config.properties